-- Copyright The Linux Foundation and each contributor to LFX.
-- SPDX-License-Identifier: MIT

-- Index the disconnect probe for hubspot_connections.
--
-- 000017 added this partial index to the six PAID-ADS connection tables and deliberately
-- skipped HubSpot, stating the reason and the trigger for revisiting it: the probe is called
-- from credsSource.systemConn below a `provider.IsPaidAds()` gate, "so hubspot_connections
-- would carry an index nothing queries and every write would pay for it. If that gate ever
-- widens, this migration widens with it."
--
-- That gate has now widened. The reserved-scope fallback serves the email channel, so a
-- foundation with no HubSpot connection of its own — which after that change is the ordinary
-- case, not the exception — reaches Disconnected() on every audience build and every email
-- dispatch. Without this index each of those is a sequential scan on the hot path of the
-- channel the change exists to enable.
--
-- Partial on `status = 'deleted'` for the same reason as 000017: the probe asks only whether a
-- project TOMBSTONED its connection, so the index covers the rows that answer it rather than
-- the whole table, and stays small while ordinary active rows cost nothing to write.
--
-- Plain CREATE INDEX rather than CONCURRENTLY, matching 000017 -- and the reason is a size
-- trade-off, NOT a constraint. An earlier version of this comment said the runner holds a
-- transaction so CONCURRENTLY could not run; that is backwards. 000013 documents the actual
-- contract: the pgx/v5 golang-migrate driver executes each migration with a bare ExecContext
-- and does NOT wrap it in a transaction, which is precisely why CONCURRENTLY is available to a
-- single-statement file like this one.
--
-- The trade-off taken instead: a plain build takes a SHARE lock, which blocks writes to
-- hubspot_connections for its duration but not reads. That table holds one row per project
-- plus the system row -- single digits today -- so the build is milliseconds, and connection
-- writes are rare operator actions rather than request-path traffic. CONCURRENTLY would avoid
-- the write lock at the cost of a second table scan, a migration that cannot be batched with
-- any other statement, and an INVALID index left behind on failure that needs manual cleanup.
-- On a table this size that machinery buys nothing. Revisit if the table ever grows.
CREATE INDEX IF NOT EXISTS idx_hubspot_connections_project_deleted ON hubspot_connections (project_id) WHERE status = 'deleted';
