// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

package design

import (
	//nolint:staticcheck // ST1001: the recommended way of using the goa DSL package is with the . import
	. "goa.design/goa/v3/dsl"
)

// ─── Email-creation wizard ───
//
// The wizard is a conversational flow over ONE brief: plan → generate two content
// variants → clone into HubSpot → set the send list → chat-driven edits. Its methods
// live on the existing briefs service (they are always scoped to a project + brief and
// reuse BriefService's already-late-bound LLM/event-scrape/HubSpot collaborators), but
// the DSL lives in this file rather than in brief.go so the wizard's surface can be
// reviewed and evolved without touching the frozen LFXV2-1940 method set.
//
// Goa refuses a second Service() block with the same name, so these methods cannot
// simply re-open Service("lfx-v2-campaign-service-briefs") here. wizardMethods is
// therefore a plain DSL helper invoked ONCE from inside brief.go's Service block —
// the same technique the file already uses for commonBriefErrors/briefErrorResponses,
// just at method granularity.
//
// ── Wire-shape constraint ──
//
// These endpoints replace a legacy service whose JSON field names an existing Angular
// frontend already depends on. The result types below therefore keep that vocabulary
// verbatim — including the FLATTENED variant_a_* fields on the generate-content
// response, which duplicate the same information the unprefixed fields carry for the
// other variant. A tidier nested {variant_a:{...},variant_b:{...}} shape would be a
// breaking change to a client this service does not own, so the flat shape is a
// deliberate contract, not an oversight.

// wizardSessionIDAttr is the wizard session identifier, generated by plan-start and
// echoed on every subsequent turn. A UUID (the table's primary key), formatted so a
// malformed value is rejected by the generated decoder rather than reaching a query.
func wizardSessionIDAttr() {
	Attribute("session_id", String, "Wizard session UUID, as returned by plan-start", func() {
		Format(FormatUUID)
	})
}

// WizardSourceEmail names the past-campaign HubSpot email a plan selected as the
// clone source / style reference.
var WizardSourceEmail = Type("wizard-source-email", func() {
	Attribute("id", String, "HubSpot marketing email id")
	Attribute("name", String, "HubSpot marketing email name")
	Required("id", "name")
})

// WizardPlanStart is plan-start's immediate, pre-work response. It carries the
// progress token BEFORE any scraping or model call happens, which is the whole point
// of splitting plan-start from plan: the client opens the SSE stream on this token and
// only then issues the (slow) plan request, so no progress frame is missed.
var WizardPlanStart = Type("wizard-plan-start", func() {
	Attribute("session_id", String, "Wizard session UUID to pass to every subsequent turn", func() {
		Format(FormatUUID)
	})
	Attribute("token", String, "Opaque progress token for the SSE stream at /projects/{project_id}/briefs/{brief_id}/wizard/progress/{token}")
	Required("session_id", "token")
})

// WizardPlanResult is what the wizard decided to do, returned synchronously by plan
// and also delivered as the `plan_done` SSE frame's result.
var WizardPlanResult = Type("wizard-plan-result", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })
	Attribute("message", String, "Human-readable summary of the plan, rendered directly in the wizard's chat transcript")
	Attribute("phase", String, "Session lifecycle phase", wizardPhaseEnum)
	// mode records HOW the plan will produce content. It is free text rather than an
	// Enum because it is a display string echoed back to the UI, and pinning it would
	// make adding a generation strategy a breaking API change.
	Attribute("mode", String, "How content will be produced for this session", func() {
		Example("reference")
	})
	Attribute("source_email", WizardSourceEmail, "Past-campaign email chosen as the clone source, when one was found")
	// stage and utm are Any for the same reason campaign `config` is: they are
	// pass-through display payloads the frontend renders, never read back typed by
	// this service. Typing them would freeze the emailstage template's field list
	// into the public API.
	Attribute("stage", Any, "Resolved event-lifecycle stage template (name, purpose, tone, CTA strategy)")
	Attribute("utm", Any, "UTM parameters that will be applied to the draft's links")
	Required("session_id", "message", "phase", "mode")
})

// wizardPhaseEnum is the session lifecycle vocabulary, shared by every result type
// that reports a phase so the values cannot drift between them.
//
//   - planning — created; the plan may or may not have run yet.
//   - content  — content has been generated and is awaiting approval/editing.
//   - cloned   — a HubSpot draft exists for this session.
//   - complete — the send list is set; the wizard has nothing left to do.
func wizardPhaseEnum() {
	Enum("planning", "content", "cloned", "complete")
}

// WizardEmailContent is one generated variant. It is NOT exposed directly on the
// generate-content response (see that method's flattened shape) — it exists so the
// two variants' field sets are defined once and cannot diverge.
var WizardEmailContent = Type("wizard-email-content", func() {
	Attribute("subject", String, "Subject line")
	Attribute("preview_text", String, "Inbox preview/preheader text")
	Attribute("html", String, "Full rendered email HTML, for preview")
	Attribute("body_html", String, "Body-only HTML, written into the HubSpot draft's first rich-text block")
	Attribute("sections", ArrayOf(Any), "Editable content blocks, in render order")
	Attribute("sponsors", ArrayOf(WizardSponsor), "Sponsor logos scraped from the event page")
	Attribute("banner_url", String, "Hero/banner image URL")
	Attribute("template_key", String, "Stage template that produced this variant")
	Attribute("stage_name", String, "Resolved stage name")
	// mode/error make a variant's FAILURE a normal, displayable result rather than an
	// error status: a stage-variant failure must never blank the reference variant, so
	// the request still answers 200 with mode "failed" on the variant that broke.
	Attribute("mode", String, "Generation outcome for this variant", func() {
		Enum("ai-generated", "failed")
	})
	Attribute("error", String, "Why this variant failed, set only when mode is \"failed\"")
	Required("subject", "preview_text", "html", "body_html", "sections", "mode")
})

// WizardSponsor is one sponsor logo scraped from the event page.
var WizardSponsor = Type("wizard-sponsor", func() {
	Attribute("name", String, "Sponsor name")
	Attribute("logo_url", String, "Sponsor logo image URL")
	Attribute("url", String, "Sponsor link target")
	Attribute("tier", String, "Sponsorship tier as the page expresses it; free text, not a normalised vocabulary")
	Required("name", "logo_url")
})

// WizardContent is generate-content's response: both variants, FLATTENED.
//
// The unprefixed fields are the reference variant (past-campaign-driven) and the
// variant_a_* fields are the stage variant (event-facts + stage-library driven). That
// asymmetry is inherited from the API this replaces and is preserved deliberately —
// see the wire-shape note at the top of this file.
var WizardContent = Type("wizard-content", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })

	Attribute("subject", String, "Reference variant subject line")
	Attribute("preview_text", String, "Reference variant preview text")
	Attribute("html", String, "Reference variant full preview HTML")
	Attribute("body_html", String, "Reference variant body-only HTML")
	Attribute("sections", ArrayOf(Any), "Reference variant editable content blocks")
	Attribute("sponsors", ArrayOf(WizardSponsor), "Sponsor logos scraped from the event page")
	Attribute("banner_url", String, "Reference variant banner image URL")

	Attribute("variant_a_subject", String, "Stage variant subject line")
	Attribute("variant_a_preview_text", String, "Stage variant preview text")
	Attribute("variant_a_html", String, "Stage variant full preview HTML")
	Attribute("variant_a_body_html", String, "Stage variant body-only HTML")
	Attribute("variant_a_sections", ArrayOf(Any), "Stage variant editable content blocks")
	Attribute("variant_a_banner_url", String, "Stage variant banner image URL")
	Attribute("variant_a_template_key", String, "Stage template that produced the stage variant")
	Attribute("variant_a_mode", String, "Stage variant outcome; \"failed\" is a normal, displayable state and does not fail the request", func() {
		Enum("ai-generated", "failed")
	})

	Required("session_id", "subject", "preview_text", "html", "body_html", "sections",
		"variant_a_subject", "variant_a_preview_text", "variant_a_html", "variant_a_body_html",
		"variant_a_sections", "variant_a_mode")
})

// WizardSections is update-sections' response — the HTML rebuilt from the blocks the
// user kept after editing. No model call is involved, so this endpoint never answers
// 503 for an unconfigured LLM.
var WizardSections = Type("wizard-sections", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })
	Attribute("body_html", String, "Body-only HTML rebuilt from the submitted sections")
	Attribute("generated_html", String, "Full preview HTML rebuilt from the submitted sections")
	Required("session_id", "body_html", "generated_html")
})

// WizardClone is clone's response. The variant_*_email_id pairs are populated when a
// variant was cloned; email_id/draft_url name the PRIMARY draft, which is whichever
// variant the caller approved.
var WizardClone = Type("wizard-clone", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })
	Attribute("message", String, "Human-readable summary of what was cloned")
	Attribute("phase", String, "Session lifecycle phase", wizardPhaseEnum)
	Attribute("email_id", String, "HubSpot id of the primary draft")
	Attribute("draft_url", String, "HubSpot app URL of the primary draft")
	Attribute("variant_a_email_id", String, "HubSpot id of the stage variant's draft")
	Attribute("variant_a_draft_url", String, "HubSpot app URL of the stage variant's draft")
	Attribute("variant_b_email_id", String, "HubSpot id of the reference variant's draft")
	Attribute("variant_b_draft_url", String, "HubSpot app URL of the reference variant's draft")
	// validation_passed is false with issues listed rather than a 4xx: the draft EXISTS
	// in HubSpot by then, so refusing the response would hide a resource that was
	// actually created. The issues are advisory and the human fixes them in HubSpot.
	Attribute("validation_passed", Boolean, "Whether every post-clone check passed")
	Attribute("validation_issues", ArrayOf(String), "Advisory problems found on the created draft; the draft exists regardless")
	Required("session_id", "message", "phase", "validation_passed")
})

// WizardSendList is set-send-list's response, mirroring what HubSpot reports back
// about the draft's recipient configuration.
var WizardSendList = Type("wizard-send-list", func() {
	Attribute("success", Boolean, "Whether the send list was applied")
	Attribute("email_id", String, "HubSpot id of the draft the list was applied to")
	Attribute("send_list_id", String, "Primary recipient list id")
	Attribute("list_type", String, "How the recipients were resolved")
	Attribute("to", Any, "HubSpot's own recipient descriptor for the draft")
	Required("success", "email_id", "send_list_id")
})

// WizardChat is one chat turn's response.
var WizardChat = Type("wizard-chat", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })
	Attribute("message", String, "The assistant's reply for this turn")
	Attribute("phase", String, "Session lifecycle phase", wizardPhaseEnum)
	Attribute("draft_url", String, "HubSpot app URL of the draft, once one exists")
	Required("session_id", "message", "phase")
})

// WizardSession is get-session's response — enough to rehydrate the UI after a reload
// or a pod change, not the full session row.
var WizardSession = Type("wizard-session", func() {
	Attribute("session_id", String, "Wizard session UUID", func() { Format(FormatUUID) })
	Attribute("phase", String, "Session lifecycle phase", wizardPhaseEnum)
	Attribute("plan", Any, "The plan result recorded for this session, when planning has run")
	Attribute("email_id", String, "HubSpot id of the primary draft, once cloned")
	Attribute("draft_url", String, "HubSpot app URL of the primary draft, once cloned")
	Required("session_id", "phase")
})

// wizardMethods declares the wizard's eight methods. It is called from inside
// brief.go's Service block; calling it anywhere else would attach the methods to the
// wrong service (or to none).
func wizardMethods() {
	Method("start-email-wizard-plan", func() {
		Description("Open an email-creation wizard session for a brief and return its progress token immediately, before any scraping or model call runs. The client opens the SSE progress stream on the returned token and only then calls plan, so no progress frame is missed. Does no work beyond creating the session row.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			// url is OPTIONAL and its absence is the common case: the brief usually
			// already carries scraped event_details, which plan reuses rather than
			// re-fetching. It is accepted so a caller can point the wizard at a
			// different page than the brief was created from.
			Attribute("url", String, "Event page to plan from; defaults to the event details already scraped onto the brief")
			Attribute("extra_context", String, "Free-text guidance appended to the planning prompt")
			Attribute("email_type", String, "Caller's own label for the kind of email being built")
			Attribute("is_transactional", Boolean, "Whether the email is transactional rather than marketing")
			Required("project_id", "brief_id")
		})
		Result(WizardPlanStart)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/plan-start")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("plan-email-wizard", func() {
		Description("Run the wizard's planning turn synchronously: resolve the event details (reusing the brief's cached scrape when present), resolve the event-lifecycle stage, and pick a past-campaign email to use as the clone source. Progress is also streamed to the session's token. Returns the plan the later turns will execute.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("url", String, "Event page to plan from; defaults to the event details already scraped onto the brief")
			Attribute("extra_context", String, "Free-text guidance appended to the planning prompt")
			Attribute("email_type", String, "Caller's own label for the kind of email being built")
			Attribute("is_transactional", Boolean, "Whether the email is transactional rather than marketing")
			Attribute("progress_token", String, "Progress token to publish this turn's SSE frames on; defaults to the session's own token")
			Required("project_id", "brief_id", "session_id")
		})
		Result(WizardPlanResult)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/plan")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("generate-wizard-content", func() {
		Description("Generate BOTH email content variants for a planned session: a reference variant driven by past campaign emails, and a stage variant driven only by scraped event facts plus the stage library. The two variants are independent model calls, so one failing leaves the other intact — a failed variant reports mode \"failed\" inside a 200 rather than failing the request. Requires the AI model to be configured; without it this endpoint returns 503.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("change_request", String, "What to change relative to the content already generated for this session; empty on the first pass")
			Attribute("progress_token", String, "Progress token to publish this turn's SSE frames on; defaults to the session's own token")
			Required("project_id", "brief_id", "session_id")
		})
		Result(WizardContent)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/generate-content")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("update-wizard-sections", func() {
		Description("Rebuild the email HTML from the content blocks the user kept after editing. Deterministic: no model call is made, so this endpoint works with the AI model unconfigured and always produces the same HTML for the same blocks.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("sections", ArrayOf(Any), "Content blocks to render, in the order they should appear")
			Required("project_id", "brief_id", "session_id", "sections")
		})
		Result(WizardSections)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/update-sections")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("clone-wizard-email", func() {
		Description("Clone the planned source email into a new HubSpot draft and write the approved variant's subject and body into it. Requires approval: an unapproved request is refused rather than silently creating a draft.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("approved", Boolean, "Must be true; the request is refused with 400 otherwise, so a draft is never created by accident")
			Attribute("subject", String, "Override the generated subject line")
			Attribute("preview_text", String, "Override the generated preview text")
			Attribute("send_list_id", String, "Apply this recipient list to the new draft in the same request")
			// variant selects which generated variant becomes the draft's content. It
			// defaults to the reference variant, matching what the unprefixed fields on
			// the generate-content response represent.
			Attribute("variant", String, "Which generated variant to write into the draft; defaults to the reference variant", func() {
				Enum("reference", "stage")
			})
			Required("project_id", "brief_id", "session_id", "approved")
		})
		Result(WizardClone)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/clone")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("set-wizard-send-list", func() {
		Description("Set the recipient (and suppression) lists on the session's HubSpot draft, recording the result on the brief's campaign audience so the ordinary dispatch path sees the same lists later. send_list_ids takes priority over send_list_id when both are given.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("email_id", String, "Draft to configure; defaults to the session's primary draft")
			Attribute("send_list_id", String, "Single recipient list id; ignored when send_list_ids is given")
			Attribute("send_list_ids", ArrayOf(String), "Recipient list ids; takes priority over send_list_id")
			Attribute("suppression_list_ids", ArrayOf(String), "Lists whose members must not receive the send")
			Required("project_id", "brief_id", "session_id")
		})
		Result(WizardSendList)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/set-send-list")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("chat-wizard-turn", func() {
		Description("Append one free-form turn to the session's conversation and answer it. A single model call with the session's persisted history as context — there is no tool-calling loop, so a chat turn never mutates the HubSpot draft. Requires the AI model to be configured; without it this endpoint returns 503.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Attribute("message", String, "The user's message for this turn")
			Required("project_id", "brief_id", "session_id", "message")
		})
		Result(WizardChat)
		commonBriefErrors()
		HTTP(func() {
			POST("/projects/{project_id}/briefs/{brief_id}/wizard/chat")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})

	Method("get-wizard-session", func() {
		Description("Read a wizard session's current phase, plan and draft references — enough to rehydrate the UI after a reload or a pod change.")
		Payload(func() {
			bearerToken()
			projectIDAttr()
			briefIDAttr()
			wizardSessionIDAttr()
			Required("project_id", "brief_id", "session_id")
		})
		Result(WizardSession)
		commonBriefErrors()
		HTTP(func() {
			GET("/projects/{project_id}/briefs/{brief_id}/wizard/session/{session_id}")
			Header("bearer_token:Authorization")
			Response(StatusOK)
			briefErrorResponses()
		})
	})
}
