// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

// Package apivalidation holds tests that exercise the GENERATED Goa request-body
// validators from OUTSIDE the generated tree (importing the exported validators),
// so no source lives under gen/ (which is DO-NOT-EDIT, regenerated by `make apigen`).
//
// This guards the Meta connection-config validation contract added in PR #38:
// account_id must match act_<digits>, page_id must be numeric. A regression that
// relaxed a pattern (letting an unusable id be stored on an active connection that can
// never dispatch) fails here. account_id stopped being Required in LFXV2-3061 (the
// credentials-only bootstrap, mirroring Google Ads) — page_id stayed Required.
package apivalidation

import (
	"strings"
	"testing"

	connsrv "github.com/linuxfoundation/lfx-v2-campaign-service/gen/http/lfx_v2_campaign_service_connections/server"
)

func strp(s string) *string { return &s }

func TestValidateMetaAdsConnectionConfig_PatternsAndRequired(t *testing.T) {
	cases := []struct {
		name      string
		body      *connsrv.MetaAdsConnectionConfigRequestBody
		wantErr   bool
		errSubstr string
	}{
		{
			name: "valid numeric ids",
			body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_193556282970417"), PageID: strp("123456789012345")},
		},
		{name: "account_id omitted (credentials-only bootstrap)", body: &connsrv.MetaAdsConnectionConfigRequestBody{PageID: strp("123")}},
		{name: "missing page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1")}, wantErr: true, errSubstr: "page_id"},
		{name: "empty page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("")}, wantErr: true, errSubstr: "page_id"},
		{name: "non-numeric page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("page-abc")}, wantErr: true, errSubstr: "page_id"},
		{name: "account_id without act_ prefix", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("193556282970417"), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "account_id non-numeric", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_foo"), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "empty account_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp(""), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		// MaxLength(64) boundary: a pattern-valid but over-long id must still 4xx, so the
		// length bound can't silently disappear on regeneration (65 = one over the cap).
		// Exactly one over the MaxLength(64) boundary: "act_" is 4 chars, so 61 digits
		// makes the ID 65 chars — this fails if regeneration relaxed the limit to 65+.
		{name: "overlong account_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_" + strings.Repeat("9", 61)), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "overlong page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp(strings.Repeat("9", 65))}, wantErr: true, errSubstr: "page_id"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := connsrv.ValidateMetaAdsConnectionConfigRequestBody(tc.body)
			assertValidation(t, err, tc.wantErr, tc.errSubstr)
		})
	}
}

func TestValidateMetaAds_CreateAndUpdate_WrapConfigValidation(t *testing.T) {
	badConfig := &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("not-numeric")}

	createBody := &connsrv.CreateMetaAdsRequestBody{
		Config:      badConfig,
		Credentials: &connsrv.MetaAdsCredentialsRequestBody{AccessToken: strp("tok"), AppSecret: strp("sec")},
	}
	if err := connsrv.ValidateCreateMetaAdsRequestBody(createBody); err == nil || !strings.Contains(err.Error(), "page_id") {
		t.Errorf("create validation must reject a non-numeric page_id, got: %v", err)
	}
	updateBody := &connsrv.UpdateMetaAdsRequestBody{Config: badConfig}
	if err := connsrv.ValidateUpdateMetaAdsRequestBody(updateBody); err == nil || !strings.Contains(err.Error(), "page_id") {
		t.Errorf("update validation must reject a non-numeric page_id, got: %v", err)
	}
}

// TestValidateCreateMetaAds_AccountIDIsOptionalAtTheTransport pins the LFXV2-3061
// contract change at the layer that actually enforces it — see
// TestValidateCreateGoogleAds_AccountIDIsOptionalAtTheTransport above for why a
// service-level test cannot prove this: the handler is reached only AFTER the
// generated validator runs, so re-adding Required("account_id") to
// MetaAdsConnectionConfig makes Goa emit a presence check again and THIS test is what
// fails, not a service test.
func TestValidateCreateMetaAds_AccountIDIsOptionalAtTheTransport(t *testing.T) {
	creds := &connsrv.MetaAdsCredentialsRequestBody{AccessToken: strp("tok"), AppSecret: strp("sec")}

	t.Run("account_id omitted is accepted", func(t *testing.T) {
		body := &connsrv.CreateMetaAdsRequestBody{
			// AccountID deliberately left nil: the key is ABSENT, not empty. page_id
			// stays Required, so it must be present for this case to isolate account_id.
			Config:      &connsrv.MetaAdsConnectionConfigRequestBody{PageID: strp("123456789012345")},
			Credentials: creds,
		}
		if body.Config.AccountID != nil {
			t.Fatal("the test case is wrong: account_id must be absent, not empty")
		}
		assertValidation(t, connsrv.ValidateCreateMetaAdsRequestBody(body), false, "")
	})

	// page_id must NOT have relaxed along with account_id.
	t.Run("page_id is still required", func(t *testing.T) {
		body := &connsrv.CreateMetaAdsRequestBody{Config: &connsrv.MetaAdsConnectionConfigRequestBody{}, Credentials: creds}
		assertValidation(t, connsrv.ValidateCreateMetaAdsRequestBody(body), true, "page_id")
	})
}

func assertValidation(t *testing.T, err error, wantErr bool, errSubstr string) {
	t.Helper()
	if wantErr {
		if err == nil {
			t.Fatalf("expected a validation error, got nil")
		}
		if errSubstr != "" && !strings.Contains(err.Error(), errSubstr) {
			t.Errorf("error should mention %q, got: %v", errSubstr, err)
		}
		return
	}
	if err != nil {
		t.Fatalf("expected no validation error, got: %v", err)
	}
}

// TestValidateLinkedinAdsConnectionConfig guards the LinkedIn connection contract added
// in the linkedin PR: account_id and org_id must be numeric (^[0-9]+$) and bounded, so a
// value the client can't interpolate into a request path/URN is a 4xx at connection
// creation rather than an async dispatch failure.
func TestValidateLinkedinAdsConnectionConfig(t *testing.T) {
	cases := []struct {
		name      string
		body      *connsrv.LinkedinAdsConnectionConfigRequestBody
		wantErr   bool
		errSubstr string
	}{
		{name: "valid numeric ids", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp("538170226"), OrgID: strp("208777")}},
		{name: "missing account_id", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{OrgID: strp("208777")}, wantErr: true, errSubstr: "account_id"},
		{name: "missing org_id", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp("538170226")}, wantErr: true, errSubstr: "org_id"},
		{name: "non-numeric account_id", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp("urn:li:sponsoredAccount:538170226"), OrgID: strp("208777")}, wantErr: true, errSubstr: "account_id"},
		{name: "non-numeric org_id (full URN)", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp("538170226"), OrgID: strp("urn:li:organization:208777")}, wantErr: true, errSubstr: "org_id"},
		{name: "empty account_id", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp(""), OrgID: strp("208777")}, wantErr: true, errSubstr: "account_id"},
		{name: "overlong org_id", body: &connsrv.LinkedinAdsConnectionConfigRequestBody{AccountID: strp("538170226"), OrgID: strp(strings.Repeat("9", 65))}, wantErr: true, errSubstr: "org_id"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assertValidation(t, connsrv.ValidateLinkedinAdsConnectionConfigRequestBody(tc.body), tc.wantErr, tc.errSubstr)
		})
	}
}

// TestValidateTwitterAdsConnectionConfig guards the X/Twitter connection contract
// (LFXV2-2642): account_id AND funding_instrument_id must both match ^[A-Za-z0-9]+$ and both
// MaxLength(64). Both are interpolated into the account-scoped request path, so a malformed value
// stored on an active connection could redirect a paid POST — validating here rejects it as a 4xx
// at creation instead of an async dispatch failure.
//
// Only funding_instrument_id is still REQUIRED. LFXV2-3319 dropped Required("account_id") to make
// X credentials-first, so an OMITTED account_id is now the legal bootstrap state — the connection
// is created with credentials alone and pointed at an account after discovery enumerates the
// choices. funding_instrument_id stays required because no discovery endpoint can supply it.
//
// The two halves are asserted separately on purpose, and the distinction is the whole point of
// the change: Goa's Required is a presence check on the JSON KEY, so relaxing it makes ABSENCE
// legal without making a malformed PRESENT value legal. "empty account_id" therefore still fails
// (Pattern rejects ""), as do the slash and overlong cases — the injection guard that motivated
// LFXV2-2642 is untouched. Only the missing-key case moved.
func TestValidateTwitterAdsConnectionConfig_PatternsAndRequired(t *testing.T) {
	cases := []struct {
		name      string
		body      *connsrv.TwitterAdsConnectionConfigRequestBody
		wantErr   bool
		errSubstr string
	}{
		{name: "valid alphanumeric ids", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb"), FundingInstrumentID: strp("lygyi")}},
		{name: "missing account_id is the credentials-first state", body: &connsrv.TwitterAdsConnectionConfigRequestBody{FundingInstrumentID: strp("lygyi")}},
		// An explicit JSON null decodes to the same nil *string as an absent key, so it is
		// accepted for the same reason. This is pinned rather than left implicit because the
		// two are indistinguishable AFTER decoding: only a test written at the decoded-body
		// level records that the equivalence was a decision. PUT is a full replace, so an
		// absent id already means "clear", and null therefore introduces no new intent.
		{name: "explicit null account_id decodes as absence", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: nil, FundingInstrumentID: strp("lygyi")}},
		{name: "missing funding_instrument_id", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb")}, wantErr: true, errSubstr: "funding_instrument_id"},
		{name: "empty account_id", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp(""), FundingInstrumentID: strp("lygyi")}, wantErr: true, errSubstr: "account_id"},
		{name: "empty funding_instrument_id", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb"), FundingInstrumentID: strp("")}, wantErr: true, errSubstr: "funding_instrument_id"},
		{name: "account_id with slash (path-injection)", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb/../x"), FundingInstrumentID: strp("lygyi")}, wantErr: true, errSubstr: "account_id"},
		{name: "funding_instrument_id with slash", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb"), FundingInstrumentID: strp("ly/gyi")}, wantErr: true, errSubstr: "funding_instrument_id"},
		{name: "overlong account_id", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp(strings.Repeat("a", 65)), FundingInstrumentID: strp("lygyi")}, wantErr: true, errSubstr: "account_id"},
		{name: "overlong funding_instrument_id", body: &connsrv.TwitterAdsConnectionConfigRequestBody{AccountID: strp("8r7gb"), FundingInstrumentID: strp(strings.Repeat("a", 65))}, wantErr: true, errSubstr: "funding_instrument_id"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := connsrv.ValidateTwitterAdsConnectionConfigRequestBody(tc.body)
			assertValidation(t, err, tc.wantErr, tc.errSubstr)
		})
	}
}

// TestValidateCreateGoogleAds_AccountIDIsOptionalAtTheTransport pins the contract change
// this PR makes, at the layer that actually enforces it.
//
// Removing Required("account_id") removed a presence check on the JSON KEY — the generated
// code was `if body.AccountID == nil`, so it rejected only OMISSION and an explicit
// `"account_id": ""` always got through. Omission is the shape the credentials-first
// bootstrap flow sends, so omission is what has to be proven acceptable.
//
// A service-level test cannot prove it: the handler is reached only AFTER the generated
// validator runs, so a validator that still rejected the omitted key would fail the request
// while every service test stayed green. Re-adding Required("account_id") to the design makes
// Goa emit ValidateGoogleAdsConnectionConfigRequestBody and call it from the create validator,
// and this test is what fails.
func TestValidateCreateGoogleAds_AccountIDIsOptionalAtTheTransport(t *testing.T) {
	creds := &connsrv.GoogleAdsCredentialsRequestBody{
		ClientID:       strp("client-id"),
		ClientSecret:   strp("client-secret"),
		RefreshToken:   strp("refresh-token"),
		DeveloperToken: strp("developer-token"),
	}

	t.Run("account_id omitted is accepted", func(t *testing.T) {
		body := &connsrv.CreateGoogleAdsRequestBody{
			// AccountID deliberately left nil: the key is ABSENT, not empty.
			Config:      &connsrv.GoogleAdsConnectionConfigRequestBody{Label: strp("LF Google Ads")},
			Credentials: creds,
		}
		if body.Config.AccountID != nil {
			t.Fatal("the test case is wrong: account_id must be absent, not empty")
		}
		assertValidation(t, connsrv.ValidateCreateGoogleAdsRequestBody(body), false, "")
	})

	// The rest of the create contract must NOT have relaxed along with it. Without these,
	// a regeneration that dropped every validation on this body would still pass above.
	t.Run("config is still required", func(t *testing.T) {
		body := &connsrv.CreateGoogleAdsRequestBody{Credentials: creds}
		assertValidation(t, connsrv.ValidateCreateGoogleAdsRequestBody(body), true, "config")
	})
	t.Run("credentials are still required", func(t *testing.T) {
		body := &connsrv.CreateGoogleAdsRequestBody{Config: &connsrv.GoogleAdsConnectionConfigRequestBody{}}
		assertValidation(t, connsrv.ValidateCreateGoogleAdsRequestBody(body), true, "credentials")
	})
	t.Run("credential validation is still wrapped", func(t *testing.T) {
		body := &connsrv.CreateGoogleAdsRequestBody{
			Config: &connsrv.GoogleAdsConnectionConfigRequestBody{},
			Credentials: &connsrv.GoogleAdsCredentialsRequestBody{
				ClientID: strp("client-id"), ClientSecret: strp("client-secret"), RefreshToken: strp("refresh-token"),
			},
		}
		assertValidation(t, connsrv.ValidateCreateGoogleAdsRequestBody(body), true, "developer_token")
	})
}
