// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

// Package apivalidation holds tests that exercise the GENERATED Goa request-body
// validators from OUTSIDE the generated tree (importing the exported validators),
// so no source lives under gen/ (which is DO-NOT-EDIT, regenerated by `make apigen`).
//
// This guards the Meta connection-config validation contract added in PR #38:
// account_id must match act_<digits>, page_id must be numeric — both Required. A
// regression that relaxed a pattern (letting an unusable id be stored on an active
// connection that can never dispatch) fails here.
package apivalidation

import (
	"strings"
	"testing"

	connsrv "github.com/linuxfoundation/lfx-v2-campaign-service/gen/http/lfx_v2_campaign_service_connections/server"
)

func strp(s string) *string { return &s }

func TestValidateMetaAdsConnectionConfig_PatternsAndRequired(t *testing.T) {
	cases := []struct {
		name      string
		body      *connsrv.MetaAdsConnectionConfigRequestBody
		wantErr   bool
		errSubstr string
	}{
		{
			name: "valid numeric ids",
			body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_193556282970417"), PageID: strp("123456789012345")},
		},
		{name: "missing account_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "missing page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1")}, wantErr: true, errSubstr: "page_id"},
		{name: "empty page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("")}, wantErr: true, errSubstr: "page_id"},
		{name: "non-numeric page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("page-abc")}, wantErr: true, errSubstr: "page_id"},
		{name: "account_id without act_ prefix", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("193556282970417"), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "account_id non-numeric", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_foo"), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "empty account_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp(""), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		// MaxLength(64) boundary: a pattern-valid but over-long id must still 4xx, so the
		// length bound can't silently disappear on regeneration (65 = one over the cap).
		{name: "overlong account_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_" + strings.Repeat("9", 65)), PageID: strp("123")}, wantErr: true, errSubstr: "account_id"},
		{name: "overlong page_id", body: &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp(strings.Repeat("9", 65))}, wantErr: true, errSubstr: "page_id"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := connsrv.ValidateMetaAdsConnectionConfigRequestBody(tc.body)
			assertValidation(t, err, tc.wantErr, tc.errSubstr)
		})
	}
}

func TestValidateMetaAds_CreateAndUpdate_WrapConfigValidation(t *testing.T) {
	badConfig := &connsrv.MetaAdsConnectionConfigRequestBody{AccountID: strp("act_1"), PageID: strp("not-numeric")}

	createBody := &connsrv.CreateMetaAdsRequestBody{
		Config:      badConfig,
		Credentials: &connsrv.MetaAdsCredentialsRequestBody{AccessToken: strp("tok"), AppSecret: strp("sec")},
	}
	if err := connsrv.ValidateCreateMetaAdsRequestBody(createBody); err == nil || !strings.Contains(err.Error(), "page_id") {
		t.Errorf("create validation must reject a non-numeric page_id, got: %v", err)
	}
	updateBody := &connsrv.UpdateMetaAdsRequestBody{Config: badConfig}
	if err := connsrv.ValidateUpdateMetaAdsRequestBody(updateBody); err == nil || !strings.Contains(err.Error(), "page_id") {
		t.Errorf("update validation must reject a non-numeric page_id, got: %v", err)
	}
}

func assertValidation(t *testing.T, err error, wantErr bool, errSubstr string) {
	t.Helper()
	if wantErr {
		if err == nil {
			t.Fatalf("expected a validation error, got nil")
		}
		if errSubstr != "" && !strings.Contains(err.Error(), errSubstr) {
			t.Errorf("error should mention %q, got: %v", errSubstr, err)
		}
		return
	}
	if err != nil {
		t.Fatalf("expected no validation error, got: %v", err)
	}
}
